language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
           CIBW_BEFORE_BUILD='pip install Cython'
    - os: osx
      language: generic
      compiler: clang
      env: PIP=pip2
           CIBW_BEFORE_BUILD='sudo pip2 install numpy Cython'

env:
  global:
    - CIBW_SKIP="cp33-*"
    - TWINE_USERNAME=ahollocou

script:
  - $PIP install cibuildwheel==0.7.1 twine
  - cibuildwheel --output-dir wheelhouse
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl