language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - CIBW_SKIP="cp33-*"

script:
  - $PIP install cibuildwheel==0.7.1
  - $PIP install Cython numpy
  - cibuildwheel --output-dir wheelhouse